"""add thr records table

Revision ID: 50f3b3061f1f
Revises: ed2fddd3bd16
Create Date: 2026-06-27 09:03:54.833871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f3b3061f1f'
down_revision: Union[str, None] = 'ed2fddd3bd16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thr_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('thr_year', sa.Integer(), nullable=False),
    sa.Column('religious_holiday', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('thr_date', sa.Date(), nullable=False),
    sa.Column('calculation_basis', sa.String(length=20), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payroll_run_id', sa.Integer(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("calculation_basis IN ('BASE_SALARY', 'PRORATED')", name='ck_thr_records_calculation_basis'),
    sa.CheckConstraint("religious_holiday IN ('IDUL_FITRI', 'CHRISTMAS', 'NYEPI', 'WAISAK')", name='ck_thr_records_religious_holiday'),
    sa.CheckConstraint("status IN ('DRAFT', 'APPROVED', 'PAID')", name='ck_thr_records_status'),
    sa.CheckConstraint('amount >= 0', name='ck_thr_records_amount'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'thr_year', 'religious_holiday', name='uq_thr_records_employee_year_holiday')
    )
    with op.batch_alter_table('thr_records', schema=None) as batch_op:
        batch_op.create_index('idx_thr_records_employee', ['employee_id'], unique=False)
        batch_op.create_index('idx_thr_records_year', ['thr_year'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thr_records', schema=None) as batch_op:
        batch_op.drop_index('idx_thr_records_year')
        batch_op.drop_index('idx_thr_records_employee')

    op.drop_table('thr_records')
    # ### end Alembic commands ###
