"""add payroll_method to tax settings and allow gross_up

Revision ID: 51322f8a2e2d
Revises: e24092f86807
Create Date: 2026-06-26 23:56:25.564647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51322f8a2e2d'
down_revision: Union[str, None] = 'e24092f86807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payroll_method', sa.String(length=20), server_default='GROSS', nullable=False))
        batch_op.create_check_constraint('ck_tax_settings_payroll_method', "payroll_method IN ('GROSS', 'GROSS_UP', 'NETT')")

    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.drop_constraint('ck_payroll_runs_payroll_method', type_='check')
        batch_op.create_check_constraint('ck_payroll_runs_payroll_method', "payroll_method IN ('GROSS', 'GROSS_UP', 'NETT')")

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint('ck_companies_payroll_method', type_='check')
        batch_op.create_check_constraint('ck_companies_payroll_method', "payroll_method IN ('GROSS', 'GROSS_UP', 'NETT')")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint('ck_companies_payroll_method', type_='check')
        batch_op.create_check_constraint('ck_companies_payroll_method', "payroll_method IN ('GROSS', 'NETT')")

    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.drop_constraint('ck_payroll_runs_payroll_method', type_='check')
        batch_op.create_check_constraint('ck_payroll_runs_payroll_method', "payroll_method IN ('GROSS', 'NETT')")

    with op.batch_alter_table('tax_settings', schema=None) as batch_op:
        batch_op.drop_constraint('ck_tax_settings_payroll_method', type_='check')
        batch_op.drop_column('payroll_method')

    # ### end Alembic commands ###
