"""add amount_basis to allowance_types

Revision ID: e24092f86807
Revises: 
Create Date: 2026-06-26 23:44:22.020834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e24092f86807'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allowance_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_basis', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allowance_types', schema=None) as batch_op:
        batch_op.drop_column('amount_basis')

    # ### end Alembic commands ###
