"""add allowance matrices for grade position department

Revision ID: ed2fddd3bd16
Revises: 51322f8a2e2d
Create Date: 2026-06-27 00:35:20.183411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed2fddd3bd16'
down_revision: Union[str, None] = '51322f8a2e2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
